CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at DATATIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATATIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
